//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Samples/Input System PS5/0.2.1-preview/Multi Contoller PS5 Input Samples/Controls/GamepadControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace UnityEngine.InputSystem.PS5.ControllerSample
{
    public partial class @GamepadControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GamepadControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GamepadControls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""1f4482e0-0ea3-423f-a106-25f890693718"",
            ""actions"": [
                {
                    ""name"": ""Press Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""373737f7-216b-4589-b0d0-f7a451209fb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press Circle"",
                    ""type"": ""Button"",
                    ""id"": ""a832638e-ecb0-476f-81d0-3b6e7895a901"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press Square"",
                    ""type"": ""Button"",
                    ""id"": ""f37a62a6-c0d3-4355-b5e5-8168157720fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press Cross"",
                    ""type"": ""Button"",
                    ""id"": ""3c967a11-4c52-4201-ab39-e39dacdff156"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dpad"",
                    ""type"": ""Value"",
                    ""id"": ""0ff3702a-0cd0-4268-9a46-1c5908370267"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press Share"",
                    ""type"": ""Button"",
                    ""id"": ""45a4dac0-60ca-4587-8f38-5945dbdcad2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press Options"",
                    ""type"": ""Button"",
                    ""id"": ""99965a92-2161-4c45-9d3f-af0ac408f100"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press Playstation Button"",
                    ""type"": ""Button"",
                    ""id"": ""a10ba43c-0471-4ff2-b1b8-57349073630c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press Left Stick"",
                    ""type"": ""Button"",
                    ""id"": ""6c5bfad7-4d9e-40cc-b6a4-51b6ab824ab8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press Right Stick"",
                    ""type"": ""Button"",
                    ""id"": ""21479c52-1a4b-49e3-b93f-05bc010e1607"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Stick Pos"",
                    ""type"": ""Value"",
                    ""id"": ""14bc6369-7f6b-425f-82f4-4119955b940f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right Stick Pos"",
                    ""type"": ""Value"",
                    ""id"": ""4df5cec8-b4d7-4094-8e10-fc0281d0875f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press Touchpad"",
                    ""type"": ""Button"",
                    ""id"": ""a6ac6068-3326-4b8c-bf8d-a5bf56e78d0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touchpad Touch 0"",
                    ""type"": ""Value"",
                    ""id"": ""95e1a408-7ec1-4151-aea2-d6dd21f70908"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touchpad Touch 1"",
                    ""type"": ""Value"",
                    ""id"": ""51b07f93-8f5b-4659-96e8-0cc55cec7df6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left Bumper"",
                    ""type"": ""Button"",
                    ""id"": ""e0fc4c1d-3ed0-48ab-b60b-ab42285e13cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right Bumper"",
                    ""type"": ""Button"",
                    ""id"": ""b82f8377-bbe4-4d17-82bb-355fec6f0ae5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""30a2157c-5fcd-4c07-a070-b03ed7f18254"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""09394738-6b8e-4093-bc8e-4a23bc7d122e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Open Debug Menu"",
                    ""type"": ""Button"",
                    ""id"": ""2003f06d-9f19-42f4-ad54-2665ce8eecac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1512195d-9c5d-4626-b855-0f5dc173bde8"",
                    ""path"": ""<DualSenseGamepadPC>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9f8eee1-2f6b-480a-994f-09eb101edd6a"",
                    ""path"": ""<PS5DualSenseGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f463a11-4f1f-4956-94ac-f93bcdbf4a50"",
                    ""path"": ""<DualSenseGamepadPC>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f02a8b7d-9e9b-45e2-94e8-83d8590a7201"",
                    ""path"": ""<PS5DualSenseGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""638309fa-c08e-488c-9f06-ecb928bd738a"",
                    ""path"": ""<DualSenseGamepadPC>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88ec5ed7-7345-417c-b7a0-01f9d8137ead"",
                    ""path"": ""<PS5DualSenseGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b1ace65-795a-42ac-9484-19ab830c2f80"",
                    ""path"": ""<DualSenseGamepadPC>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Cross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90ef49ad-a160-4ce2-abcf-49e2b6d92e10"",
                    ""path"": ""<PS5DualSenseGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Cross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5694e604-02d7-46e1-96d8-18915c1b0d14"",
                    ""path"": ""<DualSenseGamepadPC>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69b64977-1193-4ef6-814b-8c063e347ae5"",
                    ""path"": ""<PS5DualSenseGamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e04c47d0-8926-4afe-be24-3703285b50e6"",
                    ""path"": ""<DualSenseGamepadPC>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ba7cb90-7d40-415e-aa02-4890cf71fb15"",
                    ""path"": ""<PS5DualSenseGamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a875ca-3152-4e06-8821-9805b1152835"",
                    ""path"": ""<PS5DualSenseGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05585b54-7502-48b6-a992-9937730be51e"",
                    ""path"": ""<DualSenseGamepadPC>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c576eda9-e788-4dac-a235-0cc5a657949f"",
                    ""path"": ""<DualSenseGamepadPC>/systemButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Playstation Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45cf5bcf-9876-47bd-bd75-33b5c868c7b5"",
                    ""path"": ""<DualSenseGamepadPC>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Left Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19f090d7-7da7-4cce-9b3e-cd6db8bf89b3"",
                    ""path"": ""<PS5DualSenseGamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Left Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e89c9410-cca8-4d18-a33b-48c672f425cf"",
                    ""path"": ""<DualSenseGamepadPC>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Right Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ec80009-480b-4a4b-85aa-e447516d580b"",
                    ""path"": ""<PS5DualSenseGamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Right Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1330724e-900f-4406-ba2f-27914f8b68ad"",
                    ""path"": ""<DualSenseGamepadPC>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Left Stick Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24e5aef3-984e-40ae-813b-c116141f80cd"",
                    ""path"": ""<PS5DualSenseGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Left Stick Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3633c41-9657-41f1-9620-8792b85504ee"",
                    ""path"": ""<DualSenseGamepadPC>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Right Stick Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58ab7332-5479-4ec0-9cf8-63ad980936a5"",
                    ""path"": ""<PS5DualSenseGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Right Stick Pos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14b166e5-ecbe-480d-b71b-a2ee3e5e4e70"",
                    ""path"": ""<DualSenseGamepadPC>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Press Touchpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a14bb44-5f81-406b-b9cc-ee24f1c36d56"",
                    ""path"": ""<PS5DualSenseGamepad>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Press Touchpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed736912-6cfd-4f6f-a6b3-f273401367ca"",
                    ""path"": ""<PS5DualSenseGamepad>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Touchpad Touch 0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5373f8ab-c7a1-4a53-8005-d5b9fa35c29c"",
                    ""path"": ""<PS5DualSenseGamepad>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Touchpad Touch 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4078c36-b1fe-4d9f-80ad-6869b573750e"",
                    ""path"": ""<DualSenseGamepadPC>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Left Bumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""287e5bb8-9ffd-49a8-95ed-121f514735af"",
                    ""path"": ""<PS5DualSenseGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Left Bumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f685dc3-3c7f-407e-a964-125acf95fd5a"",
                    ""path"": ""<DualSenseGamepadPC>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Left Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b291f53-95d8-4496-811a-c245135ac8c7"",
                    ""path"": ""<PS5DualSenseGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Left Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a018796-9525-4c27-a0b8-f6e7bc0838f7"",
                    ""path"": ""<DualSenseGamepadPC>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Right Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be9b103-808e-4ff4-b1c4-3472e8c8ce33"",
                    ""path"": ""<PS5DualSenseGamepad>/rightTriggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Right Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1f59301-199d-488c-b42c-4da78fe7fcfd"",
                    ""path"": ""<DualSenseGamepadPC>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Right Bumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dc53be3-5420-4694-ba08-179eb5d01d3a"",
                    ""path"": ""<PS5DualSenseGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Right Bumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""30829a0a-ea4e-4a7b-a2af-ce90d93db514"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Debug Menu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""83090eed-6b2e-41b2-a865-6f4497c77207"",
                    ""path"": ""<PS5DualSenseGamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Open Debug Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""9f6a757c-f7eb-4342-a945-40c828a5b416"",
                    ""path"": ""<PS5DualSenseGamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PS5"",
                    ""action"": ""Open Debug Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<PS5DualSenseGamepad>/{Back}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""PS5"",
            ""bindingGroup"": ""PS5"",
            ""devices"": [
                {
                    ""devicePath"": ""<PS5DualSenseGamepad>/{Back}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Main
            m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
            m_Main_PressTriangle = m_Main.FindAction("Press Triangle", throwIfNotFound: true);
            m_Main_PressCircle = m_Main.FindAction("Press Circle", throwIfNotFound: true);
            m_Main_PressSquare = m_Main.FindAction("Press Square", throwIfNotFound: true);
            m_Main_PressCross = m_Main.FindAction("Press Cross", throwIfNotFound: true);
            m_Main_Dpad = m_Main.FindAction("Dpad", throwIfNotFound: true);
            m_Main_PressShare = m_Main.FindAction("Press Share", throwIfNotFound: true);
            m_Main_PressOptions = m_Main.FindAction("Press Options", throwIfNotFound: true);
            m_Main_PressPlaystationButton = m_Main.FindAction("Press Playstation Button", throwIfNotFound: true);
            m_Main_PressLeftStick = m_Main.FindAction("Press Left Stick", throwIfNotFound: true);
            m_Main_PressRightStick = m_Main.FindAction("Press Right Stick", throwIfNotFound: true);
            m_Main_LeftStickPos = m_Main.FindAction("Left Stick Pos", throwIfNotFound: true);
            m_Main_RightStickPos = m_Main.FindAction("Right Stick Pos", throwIfNotFound: true);
            m_Main_PressTouchpad = m_Main.FindAction("Press Touchpad", throwIfNotFound: true);
            m_Main_TouchpadTouch0 = m_Main.FindAction("Touchpad Touch 0", throwIfNotFound: true);
            m_Main_TouchpadTouch1 = m_Main.FindAction("Touchpad Touch 1", throwIfNotFound: true);
            m_Main_LeftBumper = m_Main.FindAction("Left Bumper", throwIfNotFound: true);
            m_Main_RightBumper = m_Main.FindAction("Right Bumper", throwIfNotFound: true);
            m_Main_LeftTrigger = m_Main.FindAction("Left Trigger", throwIfNotFound: true);
            m_Main_RightTrigger = m_Main.FindAction("Right Trigger", throwIfNotFound: true);
            m_Main_OpenDebugMenu = m_Main.FindAction("Open Debug Menu", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Main
        private readonly InputActionMap m_Main;
        private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
        private readonly InputAction m_Main_PressTriangle;
        private readonly InputAction m_Main_PressCircle;
        private readonly InputAction m_Main_PressSquare;
        private readonly InputAction m_Main_PressCross;
        private readonly InputAction m_Main_Dpad;
        private readonly InputAction m_Main_PressShare;
        private readonly InputAction m_Main_PressOptions;
        private readonly InputAction m_Main_PressPlaystationButton;
        private readonly InputAction m_Main_PressLeftStick;
        private readonly InputAction m_Main_PressRightStick;
        private readonly InputAction m_Main_LeftStickPos;
        private readonly InputAction m_Main_RightStickPos;
        private readonly InputAction m_Main_PressTouchpad;
        private readonly InputAction m_Main_TouchpadTouch0;
        private readonly InputAction m_Main_TouchpadTouch1;
        private readonly InputAction m_Main_LeftBumper;
        private readonly InputAction m_Main_RightBumper;
        private readonly InputAction m_Main_LeftTrigger;
        private readonly InputAction m_Main_RightTrigger;
        private readonly InputAction m_Main_OpenDebugMenu;
        public struct MainActions
        {
            private @GamepadControls m_Wrapper;
            public MainActions(@GamepadControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @PressTriangle => m_Wrapper.m_Main_PressTriangle;
            public InputAction @PressCircle => m_Wrapper.m_Main_PressCircle;
            public InputAction @PressSquare => m_Wrapper.m_Main_PressSquare;
            public InputAction @PressCross => m_Wrapper.m_Main_PressCross;
            public InputAction @Dpad => m_Wrapper.m_Main_Dpad;
            public InputAction @PressShare => m_Wrapper.m_Main_PressShare;
            public InputAction @PressOptions => m_Wrapper.m_Main_PressOptions;
            public InputAction @PressPlaystationButton => m_Wrapper.m_Main_PressPlaystationButton;
            public InputAction @PressLeftStick => m_Wrapper.m_Main_PressLeftStick;
            public InputAction @PressRightStick => m_Wrapper.m_Main_PressRightStick;
            public InputAction @LeftStickPos => m_Wrapper.m_Main_LeftStickPos;
            public InputAction @RightStickPos => m_Wrapper.m_Main_RightStickPos;
            public InputAction @PressTouchpad => m_Wrapper.m_Main_PressTouchpad;
            public InputAction @TouchpadTouch0 => m_Wrapper.m_Main_TouchpadTouch0;
            public InputAction @TouchpadTouch1 => m_Wrapper.m_Main_TouchpadTouch1;
            public InputAction @LeftBumper => m_Wrapper.m_Main_LeftBumper;
            public InputAction @RightBumper => m_Wrapper.m_Main_RightBumper;
            public InputAction @LeftTrigger => m_Wrapper.m_Main_LeftTrigger;
            public InputAction @RightTrigger => m_Wrapper.m_Main_RightTrigger;
            public InputAction @OpenDebugMenu => m_Wrapper.m_Main_OpenDebugMenu;
            public InputActionMap Get() { return m_Wrapper.m_Main; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
            public void AddCallbacks(IMainActions instance)
            {
                if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
                @PressTriangle.started += instance.OnPressTriangle;
                @PressTriangle.performed += instance.OnPressTriangle;
                @PressTriangle.canceled += instance.OnPressTriangle;
                @PressCircle.started += instance.OnPressCircle;
                @PressCircle.performed += instance.OnPressCircle;
                @PressCircle.canceled += instance.OnPressCircle;
                @PressSquare.started += instance.OnPressSquare;
                @PressSquare.performed += instance.OnPressSquare;
                @PressSquare.canceled += instance.OnPressSquare;
                @PressCross.started += instance.OnPressCross;
                @PressCross.performed += instance.OnPressCross;
                @PressCross.canceled += instance.OnPressCross;
                @Dpad.started += instance.OnDpad;
                @Dpad.performed += instance.OnDpad;
                @Dpad.canceled += instance.OnDpad;
                @PressShare.started += instance.OnPressShare;
                @PressShare.performed += instance.OnPressShare;
                @PressShare.canceled += instance.OnPressShare;
                @PressOptions.started += instance.OnPressOptions;
                @PressOptions.performed += instance.OnPressOptions;
                @PressOptions.canceled += instance.OnPressOptions;
                @PressPlaystationButton.started += instance.OnPressPlaystationButton;
                @PressPlaystationButton.performed += instance.OnPressPlaystationButton;
                @PressPlaystationButton.canceled += instance.OnPressPlaystationButton;
                @PressLeftStick.started += instance.OnPressLeftStick;
                @PressLeftStick.performed += instance.OnPressLeftStick;
                @PressLeftStick.canceled += instance.OnPressLeftStick;
                @PressRightStick.started += instance.OnPressRightStick;
                @PressRightStick.performed += instance.OnPressRightStick;
                @PressRightStick.canceled += instance.OnPressRightStick;
                @LeftStickPos.started += instance.OnLeftStickPos;
                @LeftStickPos.performed += instance.OnLeftStickPos;
                @LeftStickPos.canceled += instance.OnLeftStickPos;
                @RightStickPos.started += instance.OnRightStickPos;
                @RightStickPos.performed += instance.OnRightStickPos;
                @RightStickPos.canceled += instance.OnRightStickPos;
                @PressTouchpad.started += instance.OnPressTouchpad;
                @PressTouchpad.performed += instance.OnPressTouchpad;
                @PressTouchpad.canceled += instance.OnPressTouchpad;
                @TouchpadTouch0.started += instance.OnTouchpadTouch0;
                @TouchpadTouch0.performed += instance.OnTouchpadTouch0;
                @TouchpadTouch0.canceled += instance.OnTouchpadTouch0;
                @TouchpadTouch1.started += instance.OnTouchpadTouch1;
                @TouchpadTouch1.performed += instance.OnTouchpadTouch1;
                @TouchpadTouch1.canceled += instance.OnTouchpadTouch1;
                @LeftBumper.started += instance.OnLeftBumper;
                @LeftBumper.performed += instance.OnLeftBumper;
                @LeftBumper.canceled += instance.OnLeftBumper;
                @RightBumper.started += instance.OnRightBumper;
                @RightBumper.performed += instance.OnRightBumper;
                @RightBumper.canceled += instance.OnRightBumper;
                @LeftTrigger.started += instance.OnLeftTrigger;
                @LeftTrigger.performed += instance.OnLeftTrigger;
                @LeftTrigger.canceled += instance.OnLeftTrigger;
                @RightTrigger.started += instance.OnRightTrigger;
                @RightTrigger.performed += instance.OnRightTrigger;
                @RightTrigger.canceled += instance.OnRightTrigger;
                @OpenDebugMenu.started += instance.OnOpenDebugMenu;
                @OpenDebugMenu.performed += instance.OnOpenDebugMenu;
                @OpenDebugMenu.canceled += instance.OnOpenDebugMenu;
            }

            private void UnregisterCallbacks(IMainActions instance)
            {
                @PressTriangle.started -= instance.OnPressTriangle;
                @PressTriangle.performed -= instance.OnPressTriangle;
                @PressTriangle.canceled -= instance.OnPressTriangle;
                @PressCircle.started -= instance.OnPressCircle;
                @PressCircle.performed -= instance.OnPressCircle;
                @PressCircle.canceled -= instance.OnPressCircle;
                @PressSquare.started -= instance.OnPressSquare;
                @PressSquare.performed -= instance.OnPressSquare;
                @PressSquare.canceled -= instance.OnPressSquare;
                @PressCross.started -= instance.OnPressCross;
                @PressCross.performed -= instance.OnPressCross;
                @PressCross.canceled -= instance.OnPressCross;
                @Dpad.started -= instance.OnDpad;
                @Dpad.performed -= instance.OnDpad;
                @Dpad.canceled -= instance.OnDpad;
                @PressShare.started -= instance.OnPressShare;
                @PressShare.performed -= instance.OnPressShare;
                @PressShare.canceled -= instance.OnPressShare;
                @PressOptions.started -= instance.OnPressOptions;
                @PressOptions.performed -= instance.OnPressOptions;
                @PressOptions.canceled -= instance.OnPressOptions;
                @PressPlaystationButton.started -= instance.OnPressPlaystationButton;
                @PressPlaystationButton.performed -= instance.OnPressPlaystationButton;
                @PressPlaystationButton.canceled -= instance.OnPressPlaystationButton;
                @PressLeftStick.started -= instance.OnPressLeftStick;
                @PressLeftStick.performed -= instance.OnPressLeftStick;
                @PressLeftStick.canceled -= instance.OnPressLeftStick;
                @PressRightStick.started -= instance.OnPressRightStick;
                @PressRightStick.performed -= instance.OnPressRightStick;
                @PressRightStick.canceled -= instance.OnPressRightStick;
                @LeftStickPos.started -= instance.OnLeftStickPos;
                @LeftStickPos.performed -= instance.OnLeftStickPos;
                @LeftStickPos.canceled -= instance.OnLeftStickPos;
                @RightStickPos.started -= instance.OnRightStickPos;
                @RightStickPos.performed -= instance.OnRightStickPos;
                @RightStickPos.canceled -= instance.OnRightStickPos;
                @PressTouchpad.started -= instance.OnPressTouchpad;
                @PressTouchpad.performed -= instance.OnPressTouchpad;
                @PressTouchpad.canceled -= instance.OnPressTouchpad;
                @TouchpadTouch0.started -= instance.OnTouchpadTouch0;
                @TouchpadTouch0.performed -= instance.OnTouchpadTouch0;
                @TouchpadTouch0.canceled -= instance.OnTouchpadTouch0;
                @TouchpadTouch1.started -= instance.OnTouchpadTouch1;
                @TouchpadTouch1.performed -= instance.OnTouchpadTouch1;
                @TouchpadTouch1.canceled -= instance.OnTouchpadTouch1;
                @LeftBumper.started -= instance.OnLeftBumper;
                @LeftBumper.performed -= instance.OnLeftBumper;
                @LeftBumper.canceled -= instance.OnLeftBumper;
                @RightBumper.started -= instance.OnRightBumper;
                @RightBumper.performed -= instance.OnRightBumper;
                @RightBumper.canceled -= instance.OnRightBumper;
                @LeftTrigger.started -= instance.OnLeftTrigger;
                @LeftTrigger.performed -= instance.OnLeftTrigger;
                @LeftTrigger.canceled -= instance.OnLeftTrigger;
                @RightTrigger.started -= instance.OnRightTrigger;
                @RightTrigger.performed -= instance.OnRightTrigger;
                @RightTrigger.canceled -= instance.OnRightTrigger;
                @OpenDebugMenu.started -= instance.OnOpenDebugMenu;
                @OpenDebugMenu.performed -= instance.OnOpenDebugMenu;
                @OpenDebugMenu.canceled -= instance.OnOpenDebugMenu;
            }

            public void RemoveCallbacks(IMainActions instance)
            {
                if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IMainActions instance)
            {
                foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public MainActions @Main => new MainActions(this);
        private int m_PCSchemeIndex = -1;
        public InputControlScheme PCScheme
        {
            get
            {
                if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
                return asset.controlSchemes[m_PCSchemeIndex];
            }
        }
        private int m_PS5SchemeIndex = -1;
        public InputControlScheme PS5Scheme
        {
            get
            {
                if (m_PS5SchemeIndex == -1) m_PS5SchemeIndex = asset.FindControlSchemeIndex("PS5");
                return asset.controlSchemes[m_PS5SchemeIndex];
            }
        }
        public interface IMainActions
        {
            void OnPressTriangle(InputAction.CallbackContext context);
            void OnPressCircle(InputAction.CallbackContext context);
            void OnPressSquare(InputAction.CallbackContext context);
            void OnPressCross(InputAction.CallbackContext context);
            void OnDpad(InputAction.CallbackContext context);
            void OnPressShare(InputAction.CallbackContext context);
            void OnPressOptions(InputAction.CallbackContext context);
            void OnPressPlaystationButton(InputAction.CallbackContext context);
            void OnPressLeftStick(InputAction.CallbackContext context);
            void OnPressRightStick(InputAction.CallbackContext context);
            void OnLeftStickPos(InputAction.CallbackContext context);
            void OnRightStickPos(InputAction.CallbackContext context);
            void OnPressTouchpad(InputAction.CallbackContext context);
            void OnTouchpadTouch0(InputAction.CallbackContext context);
            void OnTouchpadTouch1(InputAction.CallbackContext context);
            void OnLeftBumper(InputAction.CallbackContext context);
            void OnRightBumper(InputAction.CallbackContext context);
            void OnLeftTrigger(InputAction.CallbackContext context);
            void OnRightTrigger(InputAction.CallbackContext context);
            void OnOpenDebugMenu(InputAction.CallbackContext context);
        }
    }
}
