// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_trigger_happy_i = "CgkI07-ynroOEAIQCw"; // <GPGSID>
        public const string achievement_cube_destroyer_ii = "CgkI07-ynroOEAIQCA"; // <GPGSID>
        public const string achievement_ngamer1 = "CgkI07-ynroOEAIQDg"; // <GPGSID>
        public const string achievement_ricochet_king = "CgkI07-ynroOEAIQCg"; // <GPGSID>
        public const string leaderboard_cubes_destroyed = "CgkI07-ynroOEAIQBA"; // <GPGSID>
        public const string achievement_trigger_happy_ii = "CgkI07-ynroOEAIQDA"; // <GPGSID>
        public const string leaderboard_highest_party_wave_on_starting_level = "CgkI07-ynroOEAIQAg"; // <GPGSID>
        public const string leaderboard_best_accuracy = "CgkI07-ynroOEAIQAw"; // <GPGSID>
        public const string leaderboard_most_points_earned = "CgkI07-ynroOEAIQBQ"; // <GPGSID>
        public const string achievement_trigger_happy_iii = "CgkI07-ynroOEAIQDQ"; // <GPGSID>
        public const string achievement_cube_destroyer_i = "CgkI07-ynroOEAIQBw"; // <GPGSID>
        public const string leaderboard_highest_wave_on_starting_level = "CgkI07-ynroOEAIQAQ"; // <GPGSID>
        public const string achievement_stayin_alive = "CgkI07-ynroOEAIQBg"; // <GPGSID>
        public const string achievement_cube_destroyer_iii = "CgkI07-ynroOEAIQCQ"; // <GPGSID>

}

